### ISSUE TITLE
Implementing an extension for just grabbing cookies from 1 site is IMHO an overkill. Just a userscript should be enough

### ISSUE THREAD

**Issue by KOLANICH** [e-learning-archive/browser-extension#2]
BTW: IMHO opening a new window is not needed. What is needed is to just capture cookies from already opened and signed in coursera tab and sending it using GM.xmlHttpRequest (unfortunately `fetch` is not emplemented, but it is straightforward to implement a polyfill in a very few lines of code) to a simple and small local webserver se up by coursera-dl (if you wanna implement it, don't forget that you should bind it to 127.0.0.1, not 0.0.0.0).

**Comment by infostreams** [comment]
Hi, thanks for your suggestion. That wouldn't solve my use case though, I need this to run on computers that are not running coursera-dl themselves, and it will be used by mostly untrained people. For that use case, an extension is both simple and convenient, they will probably know how to install it and the user interface of the browser extension itself is as simple as can be. 

Also, intercepting cookies is not that easy. The CAUTH value that we're after is sent as a httpOnly cookie over a HTTPS connection. How are you going to otherwise get that value if you cannot run anything else on the user's computer?

**Comment by KOLANICH** [comment]
> is sent as a httpOnly cookie over a HTTPS connection

Thanks. That really needs webext features. I guess some api for that should be added to GM and VM.

**Comment by infostreams** [comment]
Yeah, I agree. One question though, what is GM / VM?

**Comment by KOLANICH** [comment]
https://addons.mozilla.org/en/firefox/addon/greasemonkey/
https://addons.mozilla.org/en/firefox/addon/violentmonkey/

**Comment by infostreams** [comment]
Ah, I see. Thanks!
